### ISSUE TITLE
updates for R version 3.3.2

### ISSUE THREAD

**Issue by arw36** [gjuggler/ggphylo#10]
Any expectation for further development of this package? I was unable to download for R version 3.3.2, and installation failed for `devtools::install_github("gjuggler/ggphylo")`

**Comment by gjuggler** [comment]
Unfortunately no, further development is unlikely. I'd check out https://guangchuangyu.github.io/ggtree/ which works with newer versions of ggplot2.

**Comment by arw36** [comment]
Oh, thanks. I will take a look!
