### ISSUE TITLE
Error: processing vignette 'ggphylo.Rnw' failed with diagnostics: 

### ISSUE THREAD

**Issue by tboonf** [gjuggler/ggphylo#5]
HI,

When attempting to install ggphylo using  install_github('ggphylo', 'gjuggler')

I received the error message:
Error: processing vignette 'ggphylo.Rnw' failed with diagnostics:
 chunk 7 (label = phylo5) 
Error in coord_polar(expand = F, theta = "y") : 
  unused argument(s) (expand = F)
Execution halted

Does anyone know what might be the issue?

Thanks,
:)

**Comment by gjuggler** [comment]
Ah, yeah — that's an error in the ggplot options. Do you know what version of ggplot you have installed? It looks like the 'expand' argument was added to the coord_polar function in version 0.7 (https://github.com/hadley/ggplot2/blob/master/NEWS#L1389) but it may have been subsequently removed.

I haven't played with ggphylo for awhile now. I'll have a look this weekend and get it (at the very least) building again.

**Comment by tboonf** [comment]
Hey Greg,

I was using version 2_0.9.2.1.
Thank you for looking into it.

cheers,
b

**Comment by gjuggler** [comment]
Hey — let me know how this works for you. I haven't done much in R for awhile now, so I'm a bit rusty here. But removing the expand=T argument worked for me, at least.
